sudo: required
services:
  - docker

before_install:
  - docker build -t rickhui/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true rickhui/docker-react-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-demo"
  env: "DockerReactDemo-env"
  bucket_name: "elasticbeanstalk-us-west-2-081763001095"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
